name = "anime-master-game-api"
main = "worker/index.ts"
compatibility_date = "2026-06-01"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "ROOM_OBJECTS"
class_name = "RoomDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RoomDurableObject"]

[[d1_databases]]
binding = "DB"
database_name = "anime_master_game"
database_id = "29c5a6af-b096-4be0-934d-67fbcc0a0520"
migrations_dir = "d1/migrations"

[[r2_buckets]]
binding = "IMAGE_BUCKET"
bucket_name = "anime-master-game-images"

[vars]
ALLOWED_ORIGIN = "https://anipeek.animaster.dpdns.org"
R2_IMAGE_PREFIX = "question-images"
R2_EXISTING_IMAGE_LIMIT = "50"
R2_IMAGE_STORAGE_LIMIT_BYTES = "10737418240"

[observability.logs]
enabled = true
invocation_logs = true
